import { MenuBar } from '@/common/components/MenuBar/MenuBar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ReactQueryProvider from './ReactQueryClient';
import Layout from 'antd/es/layout';
import RecoilWrapper from '@/common/components/RecoilWrapper/RecoilWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilWrapper>
          <ReactQueryProvider>
            <Layout>
              <MenuBar />
              <Layout>{children}</Layout>
            </Layout>
          </ReactQueryProvider>
        </RecoilWrapper>
      </body>
    </html>
  );
}
